# Site settings
baseurl = "https://kaichaosun.github.io/"
languageCode = "en-us"
title = "Whisperd"
theme = "hugo-cactus-theme"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-128168145-1"

# Disable comments by leaving disqusShortname empty
disqusShortname = "whisperd"

paginate = 11

[params]
	name = "Kaichao Sun"
	description = "kaichao's blog"
	bio = "Enthuse about FP, DLT."
	# Enter optionally your twitter account
	twitter = "kaichaosun"
	enableRSS = false
	enableEmailSubscription = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	# rss_subscription = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "Mark it down"
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""
	emailSubscription = "Subscribe"
	EmailSubscriptionLink = "#email-subscribe"
	EmailSubscriptionAbsoluteLink = "https://kaichao.substack.com/embed"

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://twitter.com/kaichaosun"
    github   = "https://github.com/kaichaosun"

[taxonomies]
  	category = "categories"
  	tag = "tags"
